---
trigger:
    branches:
        include:
        - develop
        - release/*
        - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: PYTHON_VERSION
    value: '3.x'

stages:
  - template: templates/stages/default.yml

  - ${{ if startsWith(variables['Build.sourceBranch'], 'refs/heads/release') }}:
      - template: templates/stages/develop.yml
  - ${{ if and(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), endsWith(variables['build.sourceBranch'], '-beta')) }}:
      - template: templates/stages/release.yml
  - ${{ if and(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), not(endsWith(variables['Build.SourceBranch'], '-beta'))) }}:
      - template: templates/stages/production.yml