---
# File: develop.yml
stages:
  - stage: "Deploy"
    displayName: "Deploy Lambdas DEV"
    dependsOn: [ "DefaultStage" ]
    variables:
      - group: "xxxxx"
    jobs:
      - job: "DeployLambdasDev"
        displayName: "Deploy Lambdas DEV"
        timeoutInMinutes: 20
        variables:
          AWS_BUCKET: "xxxxxxxxxxxx"
          AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
        steps:
          - template: steps/cache.yml
          - template: steps/bootstrap.yml
          - template: steps/deploy/update-lambda.yml
            parameters:
              local_env: "dev"
              service_connection: 'xxxxx'
