---
# File: production.yml
stages:
  - stage: "Approval"
    displayName: "Approval"
    variables:
      - group: "xxxxx"
    jobs:
      - deployment: "Approval"
        environment: "xxxxxxxxx"
        displayName: "Approval"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "waiting for approval"
                  name: Approval

  - stage: "Deploy"
    displayName: "Deploy Lambdas PRD"
    dependsOn: [ "Approval" ]
    variables:
      - group: "xxxxx"
    jobs:
      - job: "DeployLambdasPRD"
        displayName: "Deploy Lambdas PRD"
        timeoutInMinutes: 20
        variables:
          AWS_BUCKET: "xxxxxxxx"
          AWS_ACCESS_KEY_ID: $(PRD_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(PRD_AWS_SECRET_ACCESS_KEY)
        steps:
          - template: steps/cache.yml
          - template: steps/bootstrap.yml
          - template: steps/deploy/update-lambda.yml
            parameters:
              local_env: "prd"
              service_connection: 'xxxxxxxxxxx'
