---
# File: stg.yml
stages:
  - stage: "Approval"
    displayName: "Approval"
    variables:
      - group: "xxxxx"
    jobs:
      - deployment: "Approval"
        environment: "xxxxxxxxx"
        displayName: "Approval"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "waiting for approval"
                  name: Approval

  - stage: "Deploy"
    displayName: "Deploy Lambdas STG"
    dependsOn: [ "Approval" ]
    variables:
      - group: "xxxxx"
    jobs:
      - job: "DeployLambdasSTG"
        displayName: "Deploy Lambdas STG"
        timeoutInMinutes: 20
        variables:
          AWS_BUCKET: "xxxxxxx"
          AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
        steps:
          - template: steps/cache.yml
          - template: steps/bootstrap.yml
          - template: steps/deploy/update-lambda.yml
            parameters:
              local_env: "stg"
              service_connection: 'xxxxx'
