---
trigger:
  branches:
    include:
      - develop
      - release/*
      - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      - template: templates/stages/develop.yml
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release') }}:
      - template: templates/stages/release.yml
  - ${{ if and(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), not(endsWith(variables['Build.SourceBranch'], '-beta'))) }}:
      - template: templates/stages/production.yml
