---
trigger:
  batch: true
  branches:
    include:
      - develop
      - release/*
      - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - template: templates/stages/default.yml
  - ${{ if startsWith(variables['Build.sourceBranch'], 'refs/heads/develop') }}:
    - template: templates/stages/develop.yml
  - ${{ if startsWith(variables['Build.sourceBranch'], 'refs/heads/release') }}:
    - template: templates/stages/staging.yml
  - ${{ if and(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), not(endsWith(variables['Build.SourceBranch'], '-beta'))) }}:
    - template: templates/stages/production.yml
