---
# File: develop.yml
stages:
  - stage: "Develop"
    displayName: "Develop"
    variables:
      - group: "xxxxx"
    condition: succeeded()
    jobs:
      - job: "BuildWeb"
        displayName: "Build and Update"
        timeoutInMinutes: 10
        steps:
          - template: steps/setup-env.yml
            parameters:
              localEnv: "dev"
          - template: steps/web/build-web.yml
            parameters:
              extraArgs: "--web-renderer canvaskit --no-tree-shake-icons --source-maps --release"
          - template: steps/web/deploy-web.yml
            parameters:
              awsAccessKeyId: $(DEV_AWS_ACCESS_KEY_ID)
              awsSecretAccessKey: $(DEV_AWS_SECRET_ACCESS_KEY)
              accountNumber: $(DEV_AWS_ACCOUNT_NUMBER)
              bucketName: $(DEV_AWS_BUCKET_NAME)
              distributionId: $(DEV_AWS_CLOUDFRONT_DISTRIBUTION_ID)
