---
# File: release.yml
stages:
  - stage: "Approval"
    displayName: "Approval"
    variables:
      - group: "xxxxx"
    jobs:
      - deployment: 'Approval'
        environment: 'xxxxxxxxxx'
        displayName: "Approval"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "waiting for approval"
                  name: Approval

  - stage: "Production"
    displayName: "Production"
    variables:
      - group: 'xxxxx'
    condition: succeeded()
    dependsOn: [ "Approval" ]
    jobs:
      - job: "BuildWeb"
        displayName: "Build and Update"
        timeoutInMinutes: 10
        steps:
          - template: steps/setup-env.yml
            parameters:
              localEnv: 'prd'
          - template: steps/web/build-web.yml
            parameters:
              extraArgs: '--web-renderer canvaskit --no-tree-shake-icons --source-maps --release'
          - template: steps/web/deploy-web.yml
            parameters:
              awsAccessKeyId: $(PRD_AWS_ACCESS_KEY_ID)
              awsSecretAccessKey: $(PRD_AWS_SECRET_ACCESS_KEY)
              accountNumber: $(PRD_AWS_ACCOUNT_NUMBER)
              bucketName: $(PRD_AWS_BUCKET_NAME)
              distributionId: $(PRD_AWS_CLOUDFRONT_DISTRIBUTION_ID)