---
name: workflow

trigger:
  branches:
    include:
      - develop
      - release/*
      - refs/tags/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: TERRAFORM_VERSION
    value: "1.8.5"
  - name: IAC_PATH
    value: "./xxxxxxxx-iac"
  - name: CODE_PATH
    value: "./xxxxxxxx"

resources:
  repositories:
    - repository: xxxxxxxx
      type: git
      name: xxxxxxxx
      ref: "refs/heads/release/1.0.0"

stages:
  - ${{ if startsWith(variables['Build.sourceBranch'], 'refs/heads/develop') }}:
      - template: templates/stages/develop.yml
  - ${{ if startsWith(variables['Build.sourceBranch'], 'refs/heads/release') }}:
      - template: templates/stages/staging.yml
  - ${{ if startsWith(variables['build.sourceBranch'], 'refs/tags/v') }}:
      - template: templates/stages/production.yml
