# File: default.yml
stages:
  - stage: "Bootstrap"
    displayName: "Bootstrap"
    jobs:
      - job: "Bootstrap"
        displayName: "Bootstrap"
        timeoutInMinutes: 10
        steps:
          - template: steps/restore-source-checksum-cache.yml
          - template: steps/bootstrap.yml