---
# File: .azure/templates/stages/develop.yml
stages:
  - stage: "build"
    displayName: "Build"
    variables:
      - group: 'xxxxx'
    jobs:
      - job: "build"
        displayName: "Build Application"
        timeoutInMinutes: 15
        steps:
          - template: steps/restore-source-checksum-cache.yml
          - template: steps/bootstrap.yml
          - template: steps/build-and-push.yml
            parameters:
              awsCredentials: 'xxxxx'
              repositoryName: 'xxxxx'
              sourceImageTag: 'v$(Build.SourceVersion)'

  - stage: "Deploy"
    displayName: "Deploy Dev"
    dependsOn: [ "Build" ]
    variables:
      - group: 'xxxxx'
    condition: succeeded()
    jobs:
      - job: "UpdateTaskDefinition"
        displayName: "Update Task Definition"
        timeoutInMinutes: 10
        variables:
          AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
        steps:
          - template: steps/update-service.yml
            parameters:
              clusterName: 'xxxxxx'
              serviceName: 'xxxxxxxxx'
              containerName: 'xxxxxxxxx'
              tag: 'v$(Build.SourceVersion)'
              family: 'xxxxxxxxxx'
              repositoryName: 'xxxxx'
