---
# File: .azure/templates/stages/production.yml
stages:
  - stage: "build"
    displayName: "Build"
    variables:
      - group: 'xxxxx'
    jobs:
      - job: "build"
        displayName: "Build Application"
        timeoutInMinutes: 30
        steps:
          - template: steps/restore-source-checksum-cache.yml
          - template: steps/bootstrap.yml
          - template: steps/build-and-push.yml
            parameters:
              awsCredentials: 'xxxxxxxxx'
              repositoryName: 'xxxxxxxxx'
              pushTag: 'v$(Build.BuildNumber)'

  - stage: "Approval"
    displayName: "Approval"
    dependsOn: [ "Build" ]
    variables:
      - group: "xxxxx"
    condition: succeeded('Build')
    jobs:
      - deployment: 'Approval'
        environment: 'xxxxxxxxxxx'
        displayName: "Approval"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "waiting for approval"
                  name: Approval

  - stage: "Deploy"
    displayName: "Deploy PRD"
    dependsOn: [ "Approval" ]
    variables:
      - group: 'xxxxx'
    condition: succeeded()
    jobs:
      - job: "UpdateTaskDefinition"
        displayName: "Update Task Definition"
        timeoutInMinutes: 30
        variables:
          AWS_ACCESS_KEY_ID: $(PRD_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(PRD_AWS_SECRET_ACCESS_KEY)
        steps:
          - template: steps/update-service.yml
            parameters:
              clusterName: 'xxxxxxx'
              serviceName: 'xxxxxxxxxx'
              containerName: 'xxxxxxxxxxxx'
              tag: 'v$(Build.BuildNumber)'
              family: 'xxxxxxxxxxxx'
              repositoryName: 'xxxxxxxxxx'
