---
# File: .azure/templates/stages/stgelop.yml
stages:
  - stage: "build"
    displayName: "Build"
    variables:
      - group: 'xxxxx'
    jobs:
      - job: "build"
        displayName: "Build Application"
        timeoutInMinutes: 15
        steps:
          - template: steps/restore-source-checksum-cache.yml
          - template: steps/bootstrap.yml
          - template: steps/build-and-push.yml
            parameters:
              awsCredentials: 'xxxxx'
              repositoryName: 'xxxxxxxxxxxx'
              sourceImageTag: 'v$(Build.SourceVersion)'

  - stage: "Approval"
    displayName: "Approval"
    dependsOn: [ "build" ]
    variables:
      - group: "xxxxx"
    condition: succeeded('build')
    jobs:
      - deployment: 'Approval'
        environment: 'xxxxxxxxxxxx'
        displayName: "Approval"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "waiting for approval"
                  name: Approval

  - stage: "Deploy"
    displayName: "Deploy STG"
    dependsOn: [ "Approval" ]
    variables:
      - group: 'xxxxx'
    condition: succeeded()
    jobs:
      - job: "UpdateTaskDefinition"
        displayName: "Update Task Definition"
        timeoutInMinutes: 10
        variables:
          AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
        steps:
          - template: steps/update-service.yml
            parameters:
              clusterName: 'xxxxxxxxxx'
              serviceName: 'xxxxxxxxxx'
              containerName: 'xxxxxxxxxxxxx'
              tag: 'v$(Build.SourceVersion)'
              family: 'xxxxxxxxx'
              repositoryName: 'xxxxxxxxxxxxx'
