---
# File: staging.yml
stages:
  - stage: "Plan"
    displayName: "Plan"
    variables:
      - group: "xxxxxx-dev"
    condition: succeeded()
    jobs:
      - job: "Plan"
        displayName: "Plan"
        timeoutInMinutes: 50
        variables:
          ENVIRONMENT: "stg"
          AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
        steps:
          - checkout: self
          - checkout: xxxxxxxx
          - template: steps/cache.yml
          - template: steps/bootstrap.yml
          - template: steps/init.yml
          - template: steps/validate-hcl.yml
          - template: steps/plan.yml

  - stage: "Approval"
    displayName: "Approval"
    dependsOn: ["Plan"]
    variables:
      - group: "xxxxxx-dev"
    condition: succeeded('Plan')
    jobs:
      - deployment: "Approval"
        environment: "xxxxx"
        displayName: "Approval"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "waiting for approval"
                  name: Approval

  - stage: "Apply"
    displayName: "Apply"
    dependsOn: ["Approval"]
    variables:
      - group: "xxxxxx-dev"
    condition: succeeded()
    jobs:
      - job: "Apply"
        displayName: "Apply"
        timeoutInMinutes: 50
        variables:
          ENVIRONMENT: "stg"
          AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
        steps:
          - checkout: self
          - checkout: xxxxxxxx
          - template: steps/cache.yml
          - template: steps/bootstrap.yml
          - template: steps/init.yml
          - template: steps/apply.yml
